### ISSUE TITLE
‘SBLTAG_NONE’ undeclared

### ISSUE THREAD

**Issue by smartmic** [kristapsdz/sblg#13]
Compilation (`make`) failed on my system (Debian Linux i386), throwing the error below. I could not find a definition of SBLTAG in the codebase.
```
util.c: In function ‘sblg_destroy’:
util.c:1034:18: error: ‘SBLTAG_NONE’ undeclared (first use in this function)
  for (i = 0; i < SBLTAG_NONE; i++) {
                  ^
```

**Comment by kristapsdz** [comment]
Thanks, I've bundled this into a new release!  It was a typo.
