### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by echkourine25** [kristapsdz/sblg#16]
Can you tell me how to use it with markdown ? i can't get it working.
I have online markdown interpreter but when i fill html code inside article.xml installwww do not work. Thank you.

**Comment by TheMaxus** [comment]
Here's a great place to start, I wish there was a link to this on the main page https://kristaps.bsd.lv/sblg/article10.html

**Comment by kristapsdz** [comment]
I've re-added these to the webpage, thank you.
