### ISSUE TITLE
Prevent variable expansion (e.g. shell code)

### ISSUE THREAD

**Issue by markand** [kristapsdz/sblg#18]
Hey,

I'm enjoying sblg but facing a simple issue regarding code that need to embed some `${VARIABLE}`, they are interpreted by `sblg` itself and I could not find how to escape them so that `sblg` does not mangle them.

Example of input:

```
<article data-sblg-article="1">
Check my variable expansion ${PATH%.xml}.
</article>
```

The generated content will have a placeholder instead:

```
$ sblg -t template.xml -c test.xml && grep Check test.html 
Check my variable expansion .
```

Is there a way to escape those strings?

**Comment by kristapsdz** [comment]
(Sorry for taking so long to answer this...)  Yes, by just having an entity-escaped dollar sign, like `&#36;`.  In the latest version (soon to be released), using regular HTML entities will also be possible, e.g, `&dollar;`.  Thanks again for reporting this!
