### ISSUE TITLE
sblg 0.6.0 fails to build on macOS

### ISSUE THREAD

**Issue by hakoyamah** [kristapsdz/sblg#22]
Hi!
I have found that sblg (version >= 0.5.9) fails to build on macOS. It cannot find expat.
Test Environments
OS: macOS Sonoma, Monterey
CPU: x86_64 and arm64

$ ./configure
...
$ make
...
Undefined symbols for architecture arm64:
  "_XML_ErrorString", referenced from:
...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sblg] Error 1

Workaround: link -lexpat; add something like the following in configure or Makefile

if [ "$(uname)" = "Darwin" ]; then
    LDFLAGS="$LDFLAGS -lexpat"
fi

or

ifeq ($(shell uname), Darwin)
  LDADD += -lexpat
endif

**Comment by kristapsdz** [comment]
Interesting---it should just pick that up. What happens when you run `pkg-config --libs expat`? If it's empty, can you also check the return code of the command?

**Comment by hakoyamah** [comment]
% pkg-config --libs expat
-L/opt/local/lib -lexpat

I installed expat using macports instead of homebrew, so the location of the lib is /opt/local/lib.

Hiroshi

> 2024/11/18 10:03、Kristaps Dz ***@***.***>のメール:
> 
> 
> Interesting---it should just pick that up. What happens when you run `pkg-config --libs expat`? If it's empty, can you also check the return code of the command?
>

**Comment by kristapsdz** [comment]
That's weird... The Makefile uses pkg-config to specify its linker arguments, so use probably just that function that's not in mac's expat. Can you copy the output of make so I can be doubly sure? I'll have access to a sonoma machine end of the week but not now.

**Comment by hakoyamah** [comment]
OK. here you are.

<details>
[m2:~/Desktop/sblg-0.6.0 2] hako% ./configure<br>
config.log: writing...  <br>
ld: unknown options: -soname  <br>
clang: error: linker command failed with exit code 1  (use -v to see invocation)  <br>
configure.local: no (fully automatic configuration)  <br>
arc4random: yes  <br>
blowfish: no  <br>
b64_ntop: yes (with -lresolv)  <br>
capsicum: no  <br>
crypt: yes  <br>
crypt_newhash: no  <br>
endian_h: no  <br>
err: yes  <br>
explicit_bzero: no  <br>
fts: yes  <br>
getexecname: no  <br>
getprogname: yes <br>
INFTIM: no<br>
landlock: no<br>
lib_socket: yes <br>
md5: no<br>
memmem: yes <br>
memrchr: no<br>
memset_s: yes <br>
mkfifoat: yes <br>
mknodat: yes <br>
osbyteorder_h: yes <br>
PASSWORD_LEN: yes <br>
PATH_MAX: yes <br>
pledge: no<br>
program_invocation_short_name: no<br>
readpassphrase: yes <br>
reallocarray: no<br>
recallocarray: no<br>
sandbox_init: yes <br>
scan_scaled: no<br>
seccomp-filter: no<br>
setresgid: no<br>
setresuid: no<br>
sha2: no<br>
SOCK_NONBLOCK: no<br>
static: no<br>
strlcat: yes <br>
strlcpy: yes <br>
strndup: yes <br>
strnlen: yes <br>
strtonum: yes <br>
sys_byteorder_h: no<br>
sys_endian_h: no<br>
sys_mkdev_h: no<br>
sys_sysmacros_h: no<br>
sys_queue: yes <br>
sys_tree: no<br>
termios: yes <br>
timingsafe_bcmp: no<br>
unveil: no<br>
WAIT_ANY: yes <br>
__progname: yes <br>
config.h: written<br>
Makefile.configure: written<br>
[m2:~/Desktop/sblg-0.6.0 2] hako% make<br>
echo "#define VERSION \"0.6.0\"" >version.h<br>
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter    -c -o compats.o compats.c<br>
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter    -c -o main.o main.c<br>
main.c:60:6: warning: 'sandbox_init' is deprecated: first deprecated in macOS 10.8 - No longer supported [-Wdeprecated-declarations]<br>
   60 |         if (sandbox_init<br>
      |             ^<br>
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sandbox.h:48:5: note: 'sandbox_init' has been explicitly marked deprecated here<br>
   48 | int sandbox_init(const char *profile, uint64_t flags, char **errorbuf);<br>
      |     ^<br>
main.c:61:7: warning: 'kSBXProfileNoNetwork' is deprecated: first deprecated in macOS 10.8 - No longer supported [-Wdeprecated-declarations]<br>
   61 |             (kSBXProfileNoNetwork, SANDBOX_NAMED, NULL) < 0)<br>
      |              ^<br>
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sandbox.h:68:19: note: 'kSBXProfileNoNetwork' has been explicitly marked deprecated here<br>
   68 | extern const char kSBXProfileNoNetwork[];<br>
      |                   ^<br>
2 warnings generated.<br>
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter    -c -o compile.o compile.c<br>
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter    -c -o linkall.o linkall.c<br>
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter    -c -o grok.o grok.c<br>
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter    -c -o util.o util.c<br>
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter    -c -o atom.o atom.c<br>
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter    -c -o article.o article.c<br>
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter    -c -o json.o json.c<br>
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter    -c -o listtags.o listtags.c<br>
cc -o sblg compats.o main.o compile.o linkall.o grok.o util.o atom.o article.o json.o listtags.o   <br>
Undefined symbols for architecture arm64:<br>
  "_XML_ErrorString", referenced from:<br>
      _compile in compile.o<br>
      _linkall in linkall.o<br>
      _linkall_r in linkall.o<br>
      _logerr in grok.o<br>
      _atom in atom.o<br>
  "_XML_GetCurrentColumnNumber", referenced from:<br>
      _compile in compile.o<br>
      _linkall in linkall.o<br>
      _linkall_r in linkall.o<br>
      _logerrx in grok.o<br>
      _atom in atom.o<br>
  "_XML_GetCurrentLineNumber", referenced from:<br>
      _compile in compile.o<br>
      _linkall in linkall.o<br>
      _linkall_r in linkall.o<br>
      _logerrx in grok.o<br>
      _atom in atom.o<br>
  "_XML_GetErrorCode", referenced from:<br>
      _compile in compile.o<br>
      _linkall in linkall.o<br>
      _linkall_r in linkall.o<br>
      _logerr in grok.o<br>
      _atom in atom.o<br>
  "_XML_Parse", referenced from:<br>
      _compile in compile.o<br>
      _linkall in linkall.o<br>
      _linkall_r in linkall.o<br>
      _sblg_parse in grok.o<br>
      _atom in atom.o<br>
  "_XML_ParserCreate", referenced from:<br>
      _main in main.o<br>
  "_XML_ParserFree", referenced from:<br>
      _main in main.o<br>
  "_XML_ParserReset", referenced from:<br>
      _compile in compile.o<br>
      _linkall in linkall.o<br>
      _linkall_r in linkall.o<br>
      _sblg_parse in grok.o<br>
      _atom in atom.o<br>
  "_XML_SetDefaultHandlerExpand", referenced from:<br>
      _compile in compile.o<br>
      _linkall in linkall.o<br>
      _linkall_r in linkall.o<br>
      _sblg_parse in grok.o<br>
      _atom in atom.o<br>
      _tmpl_begin in atom.o<br>
      _tmpl_begin in atom.o<br>
      _tmpl_begin in atom.o<br>
      ...<br>
  "_XML_SetElementHandler", referenced from:<br>
      _compile in compile.o<br>
      _template_begin in compile.o<br>
      _article_end in compile.o<br>
      _linkall in linkall.o<br>
      _tmpl_begin in linkall.o<br>
      _tmpl_begin in linkall.o<br>
      _tmpl_begin in linkall.o<br>
      ...<br>
  "_XML_SetSkippedEntityHandler", referenced from:<br>
      _compile in compile.o<br>
      _linkall in linkall.o<br>
      _linkall_r in linkall.o<br>
      _sblg_parse in grok.o<br>
  "_XML_SetStartElementHandler", referenced from:<br>
      _sblg_parse in grok.o<br>
  "_XML_SetUserData", referenced from:<br>
      _compile in compile.o<br>
      _linkall in linkall.o<br>
      _linkall_r in linkall.o<br>
      _sblg_parse in grok.o<br>
      _atom in atom.o<br>
  "_XML_StopParser", referenced from:<br>
      _tmpl_begin in atom.o<br>
      _up_begin in atom.o<br>
      _id_begin in atom.o<br>
      _id_end in atom.o<br>
      _id_end in atom.o<br>
  "_XML_UseForeignDTD", referenced from:<br>
      _compile in compile.o<br>
      _linkall in linkall.o<br>
      _linkall_r in linkall.o<br>
      _sblg_parse in grok.o<br>
ld: symbol(s) not found for architecture arm64<br>
clang: error: linker command failed with exit code 1 (use -v to see invocation)<br>
make: *** [sblg] Error 1  <br>
</details>

**Comment by kristapsdz** [comment]
Turns out this is because the ancient GNU make on Mac OS X (for my Sonoma, 3.81 from 2006!?) doesn't even support shell expansion.  Use `bmake` or update GNU make with homebrew.

**Comment by hakoyamah** [comment]
Thanks!


Hiroshi
