### ISSUE TITLE
article-name/index.html rather than article.html

### ISSUE THREAD

**Issue by brycv** [kristapsdz/sblg#7]
As far as I can tell, there is no current way to generate articles with the URL style of:

```
http://www.example.com/blog/article-name/index.html
```

Currently, sblg generates:
```
http://www.example.com/blog/article-name.html
```

I have an existing blog that I am planning to convert to sblg but all of the articles are in the article-name/index.html format. I would rather keep it that way even though it is possible to redirect to article-name.html. Have you considered adding support for this way of generating articles?

**Comment by kristapsdz** [comment]
It'd help me to show which command in particular you'd want to output in this style, but at first glance I'd just use Makefile fu for it.  So your articles would be:

```
ARTICLES = article1.xml article2.xml article3.xml
```

And build articles in the usual way.  Then when you go to make install your blog, you'd do:

```
install:
  for f in $(ARTICLES); do \
    mkdir -p /var/www/htdocs/`basename $$f .xml` ; \
    install $$f /var/www/htdocs/`basename $$f .xml`/index.html ; \
  done
```

Or something.  Within the blog, you can refer to items using ${sblg-stripbase}/index.html and friends.

But I don't see why you can't just use article1/index.xml and build article1/index.html from it, then install those, without any of the Makefile bumbling as mentioned above.

**Comment by brycv** [comment]
Didn't think about those options. Perfect. Thank you!

**Comment by kristapsdz** [comment]
Glad I can help!  Let me know if there's anything else.  (I see you updated in the ports@ list---thanks!)

**Comment by brycv** [comment]
Will do. I'm working out how I want to set everything up to do the whole migration. I'm coming from Octopress and want to migrate all the posts with as much automation as possible. Thanks again!
